genrule (
  name="client",
  srcs = [
    '//if:service.thrift',
  ],
  bash = 'mkdir -p $OUT; thrift --gen js -out $OUT $SRCDIR/service.thrift',
  out = 'lib/if',
)

export_file(
  name='lib',
  src='lib/',
  out='client/lib/'
)
