thrift_library (
  name = 'ieng6service',
  srcs = {
    'service.thrift' : [
    	'ServerStatService',
    ],
  },
  visibility = [
    'PUBLIC',
  ]
)

export_file(
  name='service.thrift',
  visibility = [
    'PUBLIC',
  ]
)
